baseurl = "https://www.rye-catcher.codes/"
title = "Rat's blog"
copyright = "Copyright &copy; 2020 - Rat"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Rat"
    github = "Rye-Catcher"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    #twitter = "username"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    tagline = "An unexamined life is not worth living"
    description = "Rat's 2nd blog"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    utterancesRepo = "Rye-Catcher/hugo-blog"
    utterancesIssueTerm = "url"
    homepageLength = 30
    commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

# uncomment to enable the Tags link on the main toolbar
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 1

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 1
